### ISSUE TITLE
Commit ee5fafd causes AOSP build to skip dataservices

### ISSUE THREAD

**Issue by japalvia** [sonyxperiadev/vendor-qcom-opensource-dataservices#10]
This change seems to cause several platforms to be skipped during building AOSP 7.1. The resulting library is now missing from my (shinano) build and logcat shows:
`CANNOT LINK EXECUTABLE "/system/vendor/bin/netmgrd": library "librmnetctl.so" not found`

Looking at where PRODUCT_PLATFORM_SOD is set:
```
$ grep -Ir PRODUCT_PLATFORM_SOD android/device/sony/
android/device/sony/kanuti/PlatformConfig.mk:PRODUCT_PLATFORM_SOD := true
android/device/sony/loire/PlatformConfig.mk:PRODUCT_PLATFORM_SOD := true
```
My guess is that https://github.com/sonyxperiadev/device-sony-shinano/blob/n-mr0/PlatformConfig.mk should now set `PRODUCT_PLATFORM_SOD := true`?

**Comment by jerpelea** [comment]
yes
it needs to be set in each platform
please PR

**Comment by japalvia** [comment]
Will do. By the way, what does 'SOD' stand for? Software on device?

**Comment by jerpelea** [comment]
I already fixed it on all platforms!
Sony Open Devices

**Comment by japalvia** [comment]
Thanks, I can see the change in the device repos.
